CREATE VIEW EMPLOYEE_CATALOGUE_VIEW AS
SELECT * FROM Employee_catalogue;

CREATE VIEW PASSPORT_CATALOGUE_VIEW AS
SELECT * FROM Passport_catalogue;

CREATE VIEW POST_CATALOGUE_VIEW AS
SELECT * FROM Post_catalogue;

CREATE VIEW RATE_CATALOGUE_VIEW AS
SELECT * FROM Rate_catalogue;

CREATE VIEW SCHEDULE_TEMPLATE_VIEW AS
SELECT * FROM Schedule_template;

CREATE VIEW WORKTIME_CATALOGUE_VIEW AS
SELECT * FROM Worktime_catalogue;

CREATE VIEW CONTACT_CATALOGUE_VIEW AS
SELECT * FROM Contact_catalogue;

CREATE VIEW CONTRACTOR_CATALOGUE_VIEW AS
SELECT * FROM Contractor_catalogue;

CREATE VIEW WORKLOG_VIEW AS
SELECT * FROM Worklog;

CREATE VIEW WEEKLY_REPORT_VIEW AS
SELECT * FROM Weekly_report;

CREATE VIEW ABSENCE_VIEW AS
SELECT * FROM Absence;

